### ISSUE TITLE
i found a bug 🐛  on your project

### ISSUE THREAD

**Issue by Danushan99** [Tech-crisis/e-commerce-project#6]

**Comment by akiakash** [comment]
whats the bug & where it is located ?

**Comment by Danushan99** [comment]
u did not remove default comments on readme.md file 
thes comments are automatically generated by react builder 
so u can change that and document properly @akiakash

**Comment by akiakash** [comment]
okay definitely i will fix it mr.  @Danushan99

**Comment by Danushan99** [comment]
ok sir have a nice day u can close this issu now 🎯❤️🔥

**Comment by akiakash** [comment]
okay done
